{
 "title": "SLS_Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 }, "options": { "content": "# SLS-Dashboard\n" } },
  {
   "title": "Aktueller Prozess",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Process Monitoring\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Aktuelle Leistung (W)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatur (°C)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tempBuilding\" or r[\"_field\"] == \"tempFaser\" or r[\"_field\"] == \"tempNozzle\" or r[\"_field\"] == \"tempSurface\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Aktuelle Temperatur (°C)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> last()\n  |> group(columns: [\"_measurement\", \"_field\"])"
    }
   ]
  }
 ]
}