{
 "title": "SLS_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://www.wbk.kit.edu/wbkintern/Forschung/Projekte/SyProLei/img/Logo.png\" width=\"160\"/><center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 4, "y": 0 },
   "options": {
    "content": "<center> <font size=12>SLS-Dashboard</font><center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://www.aim-d.de/wp-content/uploads/WBK_rgb_D.jpg\" width=\"160\"/><center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 3 },
   "options": {
    "content": "<center><font size=6>Bauteilinformationen</font></center>"
   }
  },
  {
   "title": "Bauteilnummer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Component Info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"component\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pulvervolumen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Component Info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"volumePowder\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pulvergewicht",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Component Info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weightPowder\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Faserlänger (cm)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Component Info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lengthFiber\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Schichtdicke",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Component Info\")\n  |> filter(fn: (r) => r[\"_field\"] == \"thicknessLayer\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 8 },
   "options": {
    "content": "<center><font size=6>Prozessinformationen</font></center>"
   }
  },
  {
   "title": "Maschinenstatus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Process Monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"machineState\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Aktueller Prozess",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Process Monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"process\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Aktuelle Schicht",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Process Monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"currentLayer\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gesamtanzahl Schichten",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Process Monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalLayers\")\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Aktuelle Temperatur (°C)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> last()\n  |> group(columns: [\"_measurement\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Aktueller Prozessschritt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Process Monitoring\")\n  |> filter(fn: (r) => r[\"_field\"] == \"process\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatur (°C)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tempBuilding\" or r[\"_field\"] == \"tempFaser\" or r[\"_field\"] == \"tempNozzle\" or r[\"_field\"] == \"tempSurface\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 23 },
   "options": {
    "content": "<center><font size=6>Verbrauch und CO2-Fußabdruck</font></center>"
   }
  },
  {
   "title": "Aktuelle Gesamtleistung (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"powerTotal\")\n  |> group(columns: [\"_field\"])\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gesamtenergieverbrauch (Wh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energyTotal\")\n  |> group(columns: [\"_field\"])\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energieemissionen (kg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy Emissions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"emissionEnergy\")\n  |> group(columns: [\"_field\"])\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Emissionen Pulver (kg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Material Emission\")\n  |> filter(fn: (r) => r[\"_field\"] == \"emissionPowder\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Emissionen Faser (kg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Material Emission\")\n  |> filter(fn: (r) => r[\"_field\"] == \"emissionFiber\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gesamtemissionen (kg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy Emissions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"emissionTotal\")\n  |> group(columns: [\"_field\"])\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Aktuelle Leistung (W)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"powerMotorReservoir\" or r[\"_field\"] == \"powerMotorNozzleY\" or r[\"_field\"] == \"powerMotorNozzleX\" or r[\"_field\"] == \"powerMotorFiber\" or r[\"_field\"] == \"powerMotorDoctor\" or r[\"_field\"] == \"powerMotorBuild\" or r[\"_field\"] == \"powerLaser\" or r[\"_field\"] == \"powerInfrared\" or r[\"_field\"] == \"powerHeatingNozzle\" or r[\"_field\"] == \"powerHeatingMatFiber\" or r[\"_field\"] == \"powerHeatingMat2\" or r[\"_field\"] == \"powerHeatingMat1\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energieverbrauch (Wh)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energyHeatingMat1\" or r[\"_field\"] == \"energyHeatingMat2\" or r[\"_field\"] == \"energyHeatingMatFiber\" or r[\"_field\"] == \"energyHeatingNozzle\" or r[\"_field\"] == \"energyInfrared\" or r[\"_field\"] == \"energyLaser\" or r[\"_field\"] == \"energyMotorBuild\" or r[\"_field\"] == \"energyMotorDoctor\" or r[\"_field\"] == \"energyMotorFiber\" or r[\"_field\"] == \"energyMotorNozzleX\" or r[\"_field\"] == \"energyMotorNozzleY\" or r[\"_field\"] == \"energyMotorReservoir\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energie Emissionen (g CO2-eq)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy Emissions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"emissionMotorReservoir\" or r[\"_field\"] == \"emissionMotorNozzleY\" or r[\"_field\"] == \"emissionMotorNozzleX\" or r[\"_field\"] == \"emissionMotorFiber\" or r[\"_field\"] == \"emissionHeatingMat1\" or r[\"_field\"] == \"emissionHeatingMat2\" or r[\"_field\"] == \"emissionHeatingMatFiber\" or r[\"_field\"] == \"emissionHeatingNozzle\" or r[\"_field\"] == \"emissionInfrared\" or r[\"_field\"] == \"emissionLaser\" or r[\"_field\"] == \"emissionMotorBuild\" or r[\"_field\"] == \"emissionMotorDoctor\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gesamtemissionen (g CO2-eq)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy Emissions\" or r[\"_measurement\"] == \"Material Emission\")\n  |> filter(fn: (r) => r[\"_field\"] == \"emissionEnergy\" or r[\"_field\"] == \"emissionTotal\" or r[\"_field\"] == \"emissionMaterial\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energieverbrauch (Wh) und Temperatur (°C)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\" or r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energyTotal\" or r[\"_field\"] == \"tempBuilding\" or r[\"_field\"] == \"tempFaser\" or r[\"_field\"] == \"tempNozzle\" or r[\"_field\"] == \"tempSurface\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Aktuelle Leistung (W) und Temperatur (°C)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"SLS_Data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\" or r[\"_measurement\"] == \"Temperature\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}